{
 "title": "New dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "500ms",
 "panels": [
  {
   "title": "Throttle output histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ServoOutputRaw\" and\r\n    r._field == \"servo3Raw\"\r\n  )"
    }
   ]
  },
  {
   "title": "Height above MSL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Ahrs2\" and\r\n    r._field == \"altitude\"\r\n  )"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Wind\" and\r\n    r._field == \"speed\"\r\n  )"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ahrs2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lng\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with lat: float(v: r.lat) / 10000000.0, lng: float(v: r.lng) / 10000000.0 }))\r\n  |> group()\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"AC\"])\r\n"
    }
   ]
  },
  {
   "title": "Height above terrain",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"TerrainReport\" and\r\n    r._field == \"currentHeight\"\r\n  )"
    }
   ]
  }
 ]
}