FROM node:18-alpine
ARG TS_NODE_VERSION=10.7.0

WORKDIR /src/app

RUN \
    npm update -g npm && \
    npm install --location=global typescript && \
    npm install --location=global ts-node@${TS_NODE_VERSION} && \
    npm install --location=global tslib @types/node && \
    ts-node --version

COPY . ./

RUN npm install

# Set environment variables 
ENV MAVLINK_ADDRESS=host.docker.internal 
ENV MAVLINK_PORT=5763 
ENV INFLUXDB_STRING=http://host.docker.internal:8086 
ENV INFLUXDB_TOKEN=SECURETOKEN

ENTRYPOINT ["ts-node", "mav.ts"]